export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIELD = 'GET_USERS_FAIELD';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';